root = Size.find(1)
root.children.create(size:"23.5cm以下")
root.children.create(size:"24cm")
root.children.create(size:"24.5cm")
root.children.create(size:"25cm")
root.children.create(size:"25.5cm")
root.children.create(size:"26cm")
root.children.create(size:"26.5cm")
root.children.create(size:"27cm")
root.children.create(size:"27.5cm")
root.children.create(size:"28cm")
root.children.create(size:"28.5cm")
root.children.create(size:"29cm")
root.children.create(size:"29.5cm")
root.children.create(size:"30cm")
root.children.create(size:"30.5cm")
root.children.create(size:"31cm以上")


